---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Каталевский
- type: directory
  path: content/news
  label: News
  create: documents
  match: "**/*"
  templates:
  - news-post
- type: directory
  path: content/reports
  label: Reports
  create: documents
  match: "**/*"
  templates:
  - report
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
